<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_BusinessName</name>
   <tag></tag>
   <elementGuidId>bf416d9c-e7cc-4b26-afed-65488f1b87d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_merchant_name']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;user_merchant_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;user_merchant_name&quot;]</value>
   </webElementProperties>
</WebElementEntity>
